# Generated by Django 5.2.7 on 2025-12-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dynamic_data', models.JSONField(default=dict)),
            ],
        ),
    ]
